<!--<div class="tab-block" id="menuSponsor">-->
<!--        <div role="tabpanel" class="tab-pane active" id="popular">-->
<!--            --><?php //if (isset($this->sponsorNewsData) && $this->sponsorNewsData) { ?>
<!--                <div class="list-sthumbnail">-->
<!--                    --><?php //foreach ($this->sponsorNewsData as $data) { ?>
<!--                        --><?php
//                        $name = $data[DbTable_News::COL_NEWS_TITLE];
//                        $id = $data[DbTable_News::COL_NEWS_ID];
//                        $imagePath = $data[DbTable_News::COL_NEWS_IMAGE];
//                        $thumbnail = null;
//                        if ($imagePath) {
//                            $thumbnail = $this->thumb($imagePath, 128);
//                        }
//                        $subContent = $data[DbTable_News::COL_NEWS_SUB_CONTENT];
//                        $url = $this->newsUrl($id, $name);
//                        ?>
<!--                        <div class="list-sthumbnail__item_link">-->
<!--                            <a href="--><?php //echo $url;?><!--" class="list-sthumbnail__link" title="--><?php //echo $name;?><!--">--><?php //echo $name;?><!--</a>-->
<!--                        </div>-->
<!--                        <div class="list-sthumbnail__item">-->
<!--                            <a href="--><?php //echo $url;?><!--" class="list-sthumbnail__image" title="--><?php //echo $name;?><!--">-->
<!--                                <img src="--><?php //echo $thumbnail;?><!--" alt="--><?php //echo $name;?><!--">-->
<!--                            </a>-->
<!--                            <div class="list-sthumbnail__text">-->
<!--                                <div class="list-sthumbnail__des">--><?php //echo $subContent;?><!--</div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    --><?php //}  ?>
<!--                </div>-->
<!--            --><?php //} ?>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->


<?php //if (isset($this->sponsorNewsData) && $this->sponsorNewsData) { ?>
<!--    --><?php //foreach ($this->sponsorNewsData as $data) { ?>
<!--        --><?php
//        $name = $data[DbTable_News::COL_NEWS_TITLE];
//        $id = $data[DbTable_News::COL_NEWS_ID];
//        $imagePath = $data[DbTable_News::COL_NEWS_IMAGE];
//        $thumbnail = null;
//        if ($imagePath) {
//            $thumbnail = $this->thumb($imagePath, 128);
//        }
//        $subContent = $data[DbTable_News::COL_NEWS_SUB_CONTENT];
//        $url = $this->newsUrl($id, $name);
//        ?>
<!--        <div class="panel-custom">-->
<!--            <a href="--><?php //echo $url;?><!--" title="--><?php //echo $name;?><!--">-->
<!--                <div class="header">-->
<!--                    --><?php //echo $name;?>
<!--                </div>-->
<!--            </a>-->
<!--            <div class="body">-->
<!--                <p>-->
<!--                    <a href="--><?php //echo $url;?><!--" class="list-sthumbnail__image" title="--><?php //echo $name;?><!--">-->
<!--                        <img width="100%" src="--><?php //echo $thumbnail;?><!--" alt="--><?php //echo $name;?><!--">-->
<!--                    </a>-->
<!--                </p>-->
<!--                <span>-->
<!--                   --><?php //echo $subContent;?>
<!--                </span>-->
<!--            </div>-->
<!--        </div>-->
<!--        --><?php //} ?>
<?php //} ?>
<div class="panel-custom">
    <div class="header">
        TRAVEL SERVICES
    </div>
    <div class="body">
        <p>Our wide range of products and services includes:</p>
        <ul>
            <li>
                Flight tickets
            </li>
            <li>
                Hotel
            </li>
            <li>
                Car rental
            </li>
            <li>
                Tour
            </li>
            <li>
                Service of making passport
            </li>
        </ul>
        <p>In addition, our products and services are reasonably priced and meet most users' needs.</p>
    </div>
</div>
<div class="panel-custom">
    <div class="header">
        FREQUENTLY ASKED QUESTIONS
    </div>
    <div class="body">
        <ol>
            <li><b>I need to fly quickly, so how soon can I buy my ticket?</b><br>
                - As usual, the online booking system at the ticket offices only allows booking and ticketing at
                least 3 hours before the flight.</li>
            <li><b>How to buy a tour of Vedulich.com?</b><br>
                - Register directly via website: vedulich.com or contact us directly.</li>
            <li><b>How to book a room via vedulich.com?</b><br>
                - Set directly on vedulich.com or consult directly via phone number: 0366 624 188</li>
            <li><b>How is the rental car?</b><br>
                - Price depends on the type of contract and the route you provide us, we will quote for you with
                the most suitable and cheapest price.</li>
        </ol>
    </div>
</div>
<div class="panel-custom">
    <div class="header">
        CONTACT
    </div>
    <div class="body">
        <ul>
            <li>Hotline: 0366 624 188</li>
            <li>Facebook: fb.com/dulich.ve</li>
            <li>Skype nhantran11</li>
            <li>Zalo: 0938 337 524</li>
        </ul>
    </div>
</div>
