<div class="panel-custom">
    <div class="header">
        DỊCH VỤ DU LỊCH
    </div>
    <div class="body">
        <p>Hệ thống sản phẩm và dịch vụ đa dạng của chúng tôi bao gồm:</p>
        <ul>
            <li>
                Vé máy bay
            </li>
            <li>
                Khách sạn
            </li>
            <li>
                Thuê xe
            </li>
            <li>
                Tour du lịch
            </li>
            <li>
                Dịch vụ làm passport
            </li>
        </ul>
        <p>Ngoài ra, sản phẩm và dịch vụ của chúng tôi có giá cả hợp lý và đáp ứng hầu hết nhu cầu của
            người dùng.</p>
    </div>
</div>
<div class="panel-custom">
    <div class="header">
        CÂU HỎI THƯỜNG GẶP
    </div>
    <div class="body">
        <ol>
            <li><b>Tôi cần bay gấp, vậy tôi có thể mua vé sớm nhất trước giờ bay bao nhiêu tiếng ?</b><br>
                - Theo thông lệ, hệ thống đặt chỗ online tại các phòng vé chỉ cho phép đặt và xuất vé trước giờ bay tối
                thiểu 3 tiếng.</li>
            <li><b>Khi muốn mua tour du lịch của công ty Vedulich.com phải làm như như thế nào?</b><br>
                    - Đăng kí trực tiếp qua website: vedulich.com hoặc liên hệ trực tiếp với chúng tôi.</li>
            <li><b>Làm thế nào để đặt phòng qua vedulich.com?</b><br>
                    - Đặt trực tiếp trên vedulich.com hoặc được tư vấn trực tiếp qua số điện thoại: 0366 624 188</li>
            <li><b>Giá thuê xe Ô tô thế nào?</b></br>
                - Giá phụ thuộc vào loại hợp đồng và lộ trình bạn cung cấp cho chúng tôi, chúng tôi sẽ báo giá
                cho bạn với mức phù hợp và rẻ nhất.</li>
        </ol>
    </div>
</div>
<div class="panel-custom">
    <div class="header">
        LIÊN HỆ
    </div>
    <div class="body">
        <ul>
            <li>Hotline: 0366 624 188</li>
            <li>Facebook: fb.com/dulich.ve</li>
            <li>Skype: nhantran11</li>
            <li>Zalo: 0938 337 524</li>
        </ul>
    </div>
</div>
