<!-- images banner -->
<?php echo $this->render('intro/common/header.phtml'); ?>

<section>
    <div class="breadrum-wrapper">
        <a href="/"><?php echo $this->translate->_('admin_resource_homepage');?></a> /
        <strong class="active"><?php echo $this->translate->_('admin_resource_news');?></strong>
    </div>
</section>


<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-7 col-md-8">
                <?php if ($this->pagination) { ?>
                    <?php foreach ($this->pagination as $data) { ?>
                        <?php
                        $imagePath = $data->{DbTable_News::COL_NEWS_IMAGE};
                        $thumbnail = null;
                        if ($imagePath) {
                            $thumbnail = $this->thumb($imagePath, 288);
                        }
                        $title = $data->{DbTable_News::COL_NEWS_TITLE};
                        $subContent = $data->{DbTable_News::COL_NEWS_SUB_CONTENT};
                        $url = $this->newsUrl($data[DbTable_News::COL_NEWS_ID], $title);
                        ?>
                            <article class="item col-xs-12 col-sm-6 col-md-3 mb-30-xs mb-30-xs-sm">
                                <div class="item_content">
                                    <figure class="item_img">
                                        <a href="<?php echo $url?>" title="<?php echo $title;?>"><img src="<?php echo $thumbnail?>" alt="<?php echo $title;?>"></a>
                                    </figure>
                                    <h4 class="item_title">
                                        <a href="<?php echo $url?>"><?php echo $title;?></a>
                                    </h4>
                                    <div class="item_introtext">
                                        <div class="list-block__date news-sub-content"><?php echo $subContent;?></div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </article>
                        <?php } ?>
                <?php } ?>
            </div>
            <?php echo $this->render('news/common/menu.phtml');?>
        </div>
    </div>
</section>
<?php echo $this->render('intro/common/footer.phtml'); ?>

<!--<div class="list-container">-->
<!--    <div class="row">-->
<!--        --><?php //echo $this->render('news/common/menu.phtml');?>
<!--        --><?php //if ($this->pagination) { ?>
<!--            <div class="col-lg-9 col-md-8">-->
<!--                <div class="list-container">-->
<!--                    <div class="list-block no-border">-->
<!--                        <div class="row">-->
<!--                            --><?php //foreach ($this->pagination as $data) { ?>
<!--                                --><?php
//                                $imagePath = $data->{DbTable_News::COL_NEWS_IMAGE};
//                                $thumbnail = null;
//                                if ($imagePath) {
//                                    $thumbnail = $this->thumb($imagePath, 288);
//                                }
//                                $title = $data->{DbTable_News::COL_NEWS_TITLE};
//                                $subContent = $data->{DbTable_News::COL_NEWS_SUB_CONTENT};
//                                $url = $this->newsUrl($data[DbTable_News::COL_NEWS_ID], $title);
//                                ?>
<!--                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">-->
<!--                                    <div class="list-block__item">-->
<!--                                        <a href="--><?php //echo $url?><!--" class="list-block__image" title="--><?php //echo $title;?><!--"><img src="--><?php //echo $thumbnail?><!--" alt="--><?php //echo $title;?><!--"></a>-->
<!--                                        <a href="--><?php //echo $url?><!--" class="list-block__link">--><?php //echo $title;?><!--</a>-->
<!--                                        <div class="list-block__date news-sub-content">--><?php //echo $subContent;?><!--</div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            --><?php //} ?>
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--        --><?php //} ?>
<!--    </div>-->
<!--    --><?php //echo $this->pagination; ?>
<!--</div>-->