<?php
    $name = $this->machine[DbTable_Machine::COL_MACHINE_NAME] ?? '';
    $id = $this->machine[DbTable_Machine::COL_MACHINE_ID] ?? '';
    $priority = $this->machine[DbTable_Machine::COL_MACHINE_PRIORITY] ?? '';
?>
<div class="breadcrumbs">
    <div class="col-sm-8">
        <div class="page-header float-left">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Trang chủ</a></li>
                    <li><a href="/machine">Loại máy</a></li>
                    <li class="active">Chỉnh sửa</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <div class="col-sm-6">
                    <a href="/machine"><button class="btn btn-success btn-sm">Danh sách</button></a>
                </div>
            </div>
            <form action="/machine/submit-edit" id="validate" target="ifrmEdit" method="post" class="form-horizontal">
                <div class="card-body card-block">
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="hf-email" class=" form-control-label">Tên loại máy : </label>
                        </div>
                        <div class="col-12 col-md-6">
                            <input type="text" name="name" placeholder="Danh mục..." class="form-control validate[required]" value="<?php echo $name?>">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="hf-password" class=" form-control-label">Thứ tự :</label>
                        </div>
                        <div class="col-12 col-md-6">
                            <input type="text" name="priority" placeholder="Thứ tự..." class="form-control validate[required]" value="<?php echo $priority?>">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <input type="hidden" name="id" value="<?php echo $id?>">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-dot-circle-o"></i> Submit
                    </button>
                    <button type="reset" class="btn btn-danger">
                        <i class="fa fa-ban"></i> Reset
                    </button>
                </div>
            </form>
            <iframe name="ifrmEdit" id="ifrmEdit" style="display:none"></iframe>
            <div id="model_alert" title="<?php echo $this->translate->_('common_alert_title');?>" class="dialog-box">
                <p id="contentAlert"></p>
            </div>
        </div>
    </div>
</div>