<div class="breadcrumbs">
    <div class="col-sm-8">
        <div class="page-header float-left">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Trang chủ</a></li>
                    <li><a href="/machine/edit">Danh mục</a></li>
                    <li class="active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <form>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="name" placeholder="Tìm kiếm tên danh mục..." value="<?php echo $this->name?>">
                    </div>
                    <div class="col-12 col-sm-2">
                        <select name="active" id="active" class="form-control">
                            <option value="-1">all</option>
                            <option value="1" <?php echo $this->active ==1 ? 'selected' : ''?>>Kích Hoạt</option>
                            <option value="0" <?php echo $this->active ==0 ? 'selected' : ''?>>Hủy Kết Hoạt</option>
                        </select>
                    </div>
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-outline-success">Tìm kiếm</button>
                    </div>
                </form>
                <br><br>
                <div class="col-sm-6">
                    <a href="/machine/edit"><button class="btn btn-success btn-sm">Thêm mới</button></a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"><input type="checkbox" class="check-all"></th>
                        <th scope="col">name</th>
                        <th scope="col">active</th>
                        <th scope="col">update</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <th scope="row"><input type="checkbox" class="check-items" value="<?php echo $data->{DbTable_Machine::COL_MACHINE_ID}?>"></th>
                            <td><?php echo $data->{DbTable_Machine::COL_MACHINE_NAME}?></td>
                            <td><?php echo $this->activeLabel($data->{DbTable_Machine::COL_MACHINE_ACTIVE})?></td>
                            <td>
                                <a href="/machine/edit/id/<?php echo $data->{DbTable_Machine::COL_MACHINE_ID}?>">
                                    <button type="button" class="btn btn-link">
                                        <i class="fa fa-edit"></i> Edit
                                    </button>
                                </a>
                            </td>
                        </tr>
                    <?php }?>

                    </tbody>
                </table>
                <br>
                <div class="row">
                    <div class="col-sm-12 col-md-2">
                        <div class="dataTables_info" id="bootstrap-data-table-export_info" role="status" aria-live="polite">
                            <select name="manualUpdateElement" id="manualUpdateElement" class="form-control">
                                <option value="">Chọn</option>
                                <option value="inactivate">Hủy Kích Hoạt</option>
                                <option value="activate">Kích Hoạt</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-10">
                        <?php echo $this->pagination; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
