<!-- Slide1 -->
<?php if($this->banner) {?>
    <section class="slide1">
        <div class="wrap-slick1">
            <div class="slick1">
               <?php
               $i=0;
               foreach ($this->banner as $value) { ?>
                    <div class="item-slick1 item1-slick1 banner-<?php echo $i?>" data-image="<?php echo 'upload'.$value[DbTable_Banner::COL_BANNER_IMAGE]; ?>">
                        <div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
                                <span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="fadeInDown">
                                    <?php echo $value[DbTable_Banner::COL_BANNER_CONTENT]; ?>
                                </span>

                            <h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="fadeInUp">
                                <?php echo $value[DbTable_Banner::COL_BANNER_TITLE]; ?>
                            </h2>

                            <div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
                                <!-- Button -->
                                <a href="#" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
                                    Xem Ngay
                                </a>
                            </div>
                        </div>
                    </div>
                <?php $i++;} ?>
            </div>
        </div>
    </section>
<?php } ?>

<!-- New Product -->
<?php if($this->new) { ?>
<section class="newproduct bgwhite p-t-45 p-b-105">
    <div class="container">
        <div class="sec-title p-b-60">
            <h3 class="m-text5 t-center">
                Sản phẩm mới
            </h3>
        </div>

        <!-- Slide2 -->
        <div class="wrap-slick2">
            <div class="slick2">
               <?php foreach ($this->new as $value) { ?>
                    <div class="item-slick2 p-l-15 p-r-15">
                        <!-- Block2 -->
                        <div class="block2">
                            <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
                               <!-- <img src="<?php /*echo $value[DbTable_Watch::COL_WATCH_IMAGE]; */?>" alt="IMG-PRODUCT">-->
                                <?php echo $this->image($value[DbTable_Watch::COL_WATCH_IMAGE])?>
                                <div class="block2-overlay trans-0-4">
                                    <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
                                        <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                                        <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                                    </a>

                                    <div class="block2-btn-addcart w-size1 trans-0-4">
                                        <!-- Button -->
                                        <a href="/detail-watch-<?php echo $value[DbTable_Watch::COL_WATCH_ID]; ?>.html">
                                            <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                                                Xem sản phẩm
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="block2-txt p-t-20">
                                <a href="/detail-watch-<?php echo $value[DbTable_Watch::COL_WATCH_ID]; ?>.html" class="block2-name dis-block s-text3 p-b-5">
                                   <?php echo $value[DbTable_Watch::COL_WATCH_NAME]; ?>
                                </a>

                                <span class="block2-price m-text6 p-r-5">
                                    <?php echo $value[DbTable_Watch::COL_WATCH_PRICE].' VND';?>
                                </span>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>

    </div>
</section>
<?php } ?>
<!-- Banner2 -->
<?php if($this->upcoming) { ?>
    <section class="banner2 bg5 p-t-55 p-b-55">
        <div class="container">
            <div class="sec-title p-b-52">
                <h3 class="m-text5 t-center">
                    Sản phẩm Sắp ra mắt
                </h3>
            </div>
            <?php foreach ($this->upcoming as $key => $value) { ?>
            <div class="row">
                <?php if($key%2==0){ ?>
                <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
                    <div class="hov-img-zoom pos-relative">
                        <?php echo $this->image($value[DbTable_Watch::COL_WATCH_IMAGE])?>

                        <div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">

                            <h3 class="l-text1 fs-35-sm">
                                <?php echo $value[DbTable_Watch::COL_WATCH_NAME]; ?>
                            </h3>

                            <a href="/detail-watch-<?php echo $value[DbTable_Watch::COL_WATCH_ID]; ?>.html" class="s-text4 hov2 p-t-20">
                                Nhấn vào để xem
                            </a>
                        </div>
                    </div>
                </div>
                <?php } else{ ?>
                    <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
                        <div class="bgwhite hov-img-zoom pos-relative p-b-20per-ssm">
                            <?php echo $this->image($value[DbTable_Watch::COL_WATCH_IMAGE])?>

                            <div class="ab-t-l sizefull flex-col-c-b p-l-15 p-r-15 p-b-20">
                                <div class="t-center">
                                    <a href="product-detail.html" class="dis-block s-text3 p-b-5">
                                      <?php echo $value[DbTable_Watch::COL_WATCH_NAME]; ?>
                                    </a>


                                    <span class="block2-newprice m-text8">
                                            <?php echo $value[DbTable_Watch::COL_WATCH_PRICE]; ?>
                                    </span>
                                </div>

                                <div class="flex-c-m p-t-44 p-t-30-xl">
                                    <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                                            <span class="m-text10 p-b-1 days">
                                                69
                                            </span>

                                        <span class="s-text5">
                                                Ngày
                                            </span>
                                    </div>

                                    <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                                            <span class="m-text10 p-b-1 hours">
                                                04
                                            </span>

                                        <span class="s-text5">
                                                Giờ
                                            </span>
                                    </div>

                                    <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                                            <span class="m-text10 p-b-1 minutes">
                                                32
                                            </span>

                                        <span class="s-text5">
                                                Phút
                                            </span>
                                    </div>

                                    <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                                            <span class="m-text10 p-b-1 seconds">
                                                05
                                            </span>

                                        <span class="s-text5">
                                                Giây
                                            </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                   <?php }?>
                </div>
            <?php } ?>
        </div>
    </section>
<?php } ?>


<!-- Blog -->
<?php if($this->hot) { ?>
    <section class="blog bgwhite p-t-94 p-b-65">
        <div class="container">
            <div class="sec-title p-b-52">
                <h3 class="m-text5 t-center">
                    Sản phẩm nổi bật
                </h3>
            </div>

            <div class="row">
                <?php foreach ($this->hot as $value) { ?>
                    <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
                        <!-- Block3 -->
                        <div class="block3">
                            <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
                                <?php echo $this->image($value[DbTable_Watch::COL_WATCH_IMAGE])?>
                            </a>

                            <div class="block3-txt p-t-14">

                                <div class="block2-txt p-t-20">
                                    <a href="/detail-watch-<?php echo $value[DbTable_Watch::COL_WATCH_ID]; ?>.html" class="block2-name dis-block s-text3 p-b-5">
                                        <?php echo $value[DbTable_Watch::COL_WATCH_NAME]; ?>
                                    </a>

                                    <span class="block2-price m-text6 p-r-5">
                                         <?php echo $value[DbTable_Watch::COL_WATCH_PRICE].' VND';?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>

<!-- Shipping -->
<section class="shipping bgwhite p-t-62 p-b-46">
    <div class="flex-w p-l-15 p-r-15">
        <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
            <h4 class="m-text12 t-center">
                Free Delivery Worldwide
            </h4>

            <a href="#" class="s-text11 t-center">
                Click here for more info
            </a>
        </div>

        <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
            <h4 class="m-text12 t-center">
                30 Days Return
            </h4>

            <span class="s-text11 t-center">
					Simply return it within 30 days for an exchange.
				</span>
        </div>

        <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
            <h4 class="m-text12 t-center">
                Store Opening
            </h4>

            <span class="s-text11 t-center">
					Shop open from Monday to Sunday
				</span>
        </div>
    </div>
</section>