<section class="hidden-xs">
    <div id="key-slide" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="images/key-visual.jpg" />
                <div class="black-cover"></div>
                <div class="container">
                    <div class="carousel-caption">
                        <h1><?php echo $this->translate->_('index_travel_insurance_solution');?></h1>
                        <p class="hidden-sm"><?php echo $this->translate->_('index_finding_travel');?></p>
                        <form method="post" action="<?php echo $this->translate->_('search_now');?>">
                            <div class="form-horizontal">
<!--                                <div class="form-group">-->
<!--                                    <div class="col-sm-12 col-md-6 mb-15-xs-sm">-->
<!--                                        <input type="text" name="where" class="form-control" placeholder="--><?php //echo $this->translate->_('index_where_are_you_go');?><!--">-->
<!--                                    </div>-->
<!--                                    <div class="col-sm-12 col-md-6">-->
<!--                                        <input type="text" name="how_long" class="form-control" placeholder="--><?php //echo $this->translate->_('index_how_long');?><!--">-->
<!--                                    </div>-->
<!--                                </div>-->
                                <div class="row">
                                    <div class="col-sm-12 col-lg-6 col-lg-offset-3">
                                        <button type="submit" class="btn btn-warning btn-block"><span><?php echo $this->translate->_('index_quote_online');?></span> <span class="mdi mdi-arrow-right-box"></span></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section section-white-pattern-bg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="section-title"><?php echo $this->translate->_('index_you_need');?></h1>
                <hr class="hr-tittle">
            </div>
        </div>
        <div class="row mt-50">
            <div class="row">
                <div class="col-xs-12 col-sm-4">
                    <div class="span3">
                        <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                            <section class="">
                                <div class="service-box">
                                    <div class="extrabox">
                                        <figure class="icon"><img src="images/need-01.png" alt=""></figure>
                                    </div>
                                    <div class="service-box_body text-decoration-content">
                                        <h3 class="title"><?php echo $this->translate->_('index_need_schengen_area');?></h3>
                                        <div class="service-box_txt"><?php echo $this->translate->_('index_requirement_coverage');?></div>
                                    </div>
                                </div>
                            </section>
                        </a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="span3">
                        <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                            <section class="">
                                <div class="service-box ">
                                    <div class="extrabox">
                                        <figure class="icon"><img src="images/need-02.png" alt=""></figure>
                                    </div>
                                    <div class="service-box_body text-decoration-content">
                                        <h3 class="title"><?php echo $this->translate->_('index_need_coverage');?></h3>
                                        <div class="service-box_txt"><?php echo $this->translate->_('index_right_stay');?></div>
                                    </div>
                                </div>
                            </section>
                        </a>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="span3">
                        <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                            <section class="">
                                <div class="service-box ">
                                    <div class="extrabox">
                                        <figure class="icon"><img src="images/need-03.png" alt=""></figure>
                                    </div>
                                    <div class="service-box_body text-decoration-content">
                                        <h3 class="title"><?php echo $this->translate->_('index_need_protection');?></h3>
                                        <div class="service-box_txt"><?php echo $this->translate->_('index_pay_stay');?></div>
                                    </div>
                                </div>
                            </section>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section section-main">
    <div class="container">
        <?php echo $this->render('index/index/about-us.phtml');?>
    </div>
</section>
<section class="section section-pattern-bg">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="section-title"><?php echo $this->translate->_('index_how_insurance');?></h1>
                <hr class="hr-tittle">
            </div>
        </div>
        <div class="row mt-50">
            <div class="col-xs-12 col-sm-4">
                <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                    <div class="panel panel-default panel-01">
                        <div class="panel-heading">
                            <span><?php echo $this->translate->_('index_step_01');?></span><span class="mdi mdi-playlist-edit"></span>
                        </div>
                        <div class="panel-body text-decoration-content step">
                            <p>
                            </p>
                            <p>
                            <h3><?php echo $this->translate->_('index_step_01_title');?></h3>
                            </p>
                            <div>
                                <p>
                                    <?php echo $this->translate->_('index_step_01_content_1');?>
                                </p>
<!--                                <p>-->
<!--                                    <ol>-->
<!--                                        <li>-->
<!--                                <p>-->
<!--                                    --><?php //echo $this->translate->_('index_step_01_content_2');?><!-- <span class="text-danger">*</span>-->
<!--                                </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_3');?><!-- <span class="text-danger">*</span>-->
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_4');?><!-- <span class="text-danger">*</span>-->
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_5');?><!--<span class="text-danger">*</span>-->
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_6');?><!-- <span class="text-danger">*</span> --><?php //echo $this->translate->_('index_step_01_content_7');?>
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_8');?>
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_9');?>
<!--                                    </p>-->
<!--                                </li>-->
<!--                                <li>-->
<!--                                    <p>-->
<!--                                        --><?php //echo $this->translate->_('index_step_01_content_10');?>
<!--                                    </p>-->
<!--                                </li>-->
<!--                                </ol>-->
<!--                                </p>-->
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-4">
                <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                    <div class="panel panel-default panel-02">
                        <div class="panel-heading text-decoration-header">
                            <span><?php echo $this->translate->_('index_step_02');?></span><span class="mdi mdi-credit-card"></span>
                        </div>
                        <div class="panel-body text-decoration-content step">
                            <p>
                            </p>
                            <p>
                            <h3><?php echo $this->translate->_('index_step_02_title');?></h3>
                            </p>
                            <p>
                                <?php echo $this->translate->_('index_step_02_content');?>
                            </p>
<!--                            <div class="payment-wrapper">-->
<!--                                <img src="images/paypal.png" alt="">-->
<!--                                <img src="images/norton.png" alt="">-->
<!--                            </div>-->
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-4">
                <a href="<?php echo $this->translate->_('search_now');?>" class="text-decoration">
                    <div class="panel panel-default panel-03">
                        <div class="panel-heading text-decoration-header">
                            <span><?php echo $this->translate->_('index_step_03');?></span><span class="mdi mdi-file-download"></span>
                        </div>
                        <div class="panel-body text-decoration-content step">
                            <p>
                            </p>
                            <p>
                                <h3><?php echo $this->translate->_('index_step_03_title');?></h3>
                            </p>
                            <p>
                                <?php echo $this->translate->_('index_step_03_content_1');?>
                            </p>
<!--                            <p>-->
<!--                                <ul>-->
<!--                                    <li>-->
<!--                                        <p>-->
<!--                                            --><?php //echo $this->translate->_('index_step_03_content_2');?>
<!--                                        </p>-->
<!--                                    </li>-->
<!--                                    <li>-->
<!--                                        <p>-->
<!--                                            --><?php //echo $this->translate->_('index_step_03_content_3');?>
<!--                                        </p>-->
<!--                                    </li>-->
<!--                                    <li>-->
<!--                                        <p>-->
<!--                                            --><?php //echo $this->translate->_('index_step_03_content_4');?>
<!--                                        </p>-->
<!--                                    </li>-->
<!--                                    <li>-->
<!--                                        <p>-->
<!--                                            --><?php //echo $this->translate->_('index_step_03_content_5');?>
<!--                                        </p>-->
<!--                                     </li>-->
<!--                                </ul>-->
<!--                            </p>-->
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="section section-news">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h1 class="section-title"><?php echo $this->translate->_('index_ask_question');?></h1>
                <hr class="hr-tittle">
            </div>
        </div>
        <div class="row article mt-50">
            <div class="col-xs-6 col-md-2">
                <h5 class="article-published-date"><span class="mdi mdi-calendar"></span> <span><?php echo $this->translate->_('month_june');?></span></h5>
            </div>
            <div class="col-xs-12 col-md-9">
                <h5 class="article-title">
                    <span class="label label-lg label-default article-type mr-5">
                        <?php echo $this->translate->_('index_new');?>
                    </span>
                    <span><?php echo $this->translate->_('asked_questions_1');?></span><br>
                    <span style="font-size: 13px"><?php echo $this->translate->_('answer_1');?></span>
                </h5>
            </div>
            <div class="col-xs-6 col-md-1 hidden-xs hidden-sm">
                <a href="<?php echo $this->translate->_('search_now');?>"><button type="button" class="btn btn-sm btn-block btn-primary"><?php echo $this->translate->_('index_view');?></button></a>
            </div>
            <button type="button" class="btn btn-sm btn-primary hidden-md hidden-lg article-view-more"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
        </div>
        <div class="row article">
            <div class="col-xs-6 col-md-2">
                <h5 class="article-published-date"><span class="mdi mdi-calendar"></span> <span><?php echo $this->translate->_('month_may');?></span></h5>
            </div>
            <div class="col-xs-12 col-md-9">
                <h5 class="article-title"><span class="label label-lg label-default article-type mr-5"><?php echo $this->translate->_('index_new');?></span>
                    <span><?php echo $this->translate->_('asked_questions_2');?></span><br>
                    <span style="font-size: 13px"><?php echo $this->translate->_('answer_2');?></span>
                </h5>
            </div>
            <div class="col-xs-6 col-md-1 hidden-xs hidden-sm">
                <a href="<?php echo $this->translate->_('search_now');?>"><button type="button" class="btn btn-sm btn-block btn-primary"><?php echo $this->translate->_('index_view');?></button></a>
            </div>
            <button type="button" class="btn btn-sm btn-primary hidden-md hidden-lg article-view-more"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
        </div>
        <div class="row article">
            <div class="col-xs-6 col-md-2">
                <h5 class="article-published-date"><span class="mdi mdi-calendar"></span> <span><?php echo $this->translate->_('month_july');?></span></h5>
            </div>
            <div class="col-xs-12 col-md-9">
                <h5 class="article-title"><span class="label label-lg label-default article-type mr-5"><?php echo $this->translate->_('index_new');?></span>
                    <span><?php echo $this->translate->_('asked_questions_3');?></span><br>
                    <span style="font-size: 13px"><?php echo $this->translate->_('answer_3');?></span>
                </h5>
            </div>
            <div class="col-xs-6 col-md-1 hidden-xs hidden-sm">
                <a href="<?php echo $this->translate->_('search_now');?>"><button type="button" class="btn btn-sm btn-block btn-primary"><?php echo $this->translate->_('index_view');?></button></a>
            </div>
            <button type="button" class="btn btn-sm btn-primary hidden-md hidden-lg article-view-more"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
        </div>
        <div class="row article-more">
            <div class="col-xs-12 text-center">
                <a href="<?php echo $this->translate->_('search_now');?>"><button type="button" class="btn btn-warning"><?php echo $this->translate->_('index_read_more');?></button></a>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="places-wrapper">
                    <?php
                       if($this->locale=='vi')
                         echo '<img src="images/places-vi.jpg">';
                       else
                         echo '<img src="images/places-en.jpg">';
                     ?>
                </div>
            </div>
        </div>
    </div>
</section>



<!--Unknow it -->
<!--<section class="section section-how">-->
<!--    <div class="container">-->
<!--        --><?php //echo $this->howDoWeApproachInformation[DbTable_Content::COL_CONTENT_CONTENT]; ?>
<!--    </div>-->
<!--</section>-->
<section class="section">
    <div class="container">
        <?php echo $this->render('index/index/news.phtml');?>
        <?php echo $this->render('index/index/partner.phtml');?>
    </div>
</section>
<div id="map" style="width:100%;height:100%;">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3875.4079008507433!2d109.20749094999336!3d13.754257890298481!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x316f6cc2c31a7805%3A0x6c702d15d13a1a33!2zMTc1IENoxrDGoW5nIETGsMahbmcsIE5ndXnhu4VuIFbEg24gQ-G7qywgVGjDoG5oIHBo4buRIFF1aSBOaMahbiwgQsOsbmggxJDhu4tuaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1547803223123"
            width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>