<style>
    body {
        background: #efe9e9;
    }
    /*.col-xs-6.col-sm-2 {

        height: 80px;
        font-size: 16px;
        font-weight: bold;
        margin-bottom: 20px;
        margin-right: 5%;
        margin-left: 3%;

    }
    .col-xs-6.col-sm-2.input {
        text-align: left;

    }
    #option {

        height: 80px;

    }
    option {



    }
    select {
        border: 2px solid white;
        background: rgba(255,255,255,0.2);
        width: 120%;
    }
    input {
          width: 120%;
        height: 80px;
        border: 2px solid #000000;
        background: rgba(255,255,255,0.2);
        color: white;
        border-color: white;
    }
    input:focus {
        background: rgba(63,169,245,1.00);
    }*/
    #formSignUp
    {
        width: 50%;
        margin: 100px auto;
        padding: 20px;
        min-width: 300px;
        background: #ffffff;
    }

    #formSignUp form .avatar.label-danger {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        margin: -70px auto 0px;
        background-color: black;
        padding-top: 32px;

    }
    #formSignUp form .avatar.label-danger .img-responsive {
        height: 50%;
        width: auto;
        margin-left: 10px;

    }
    .col-xs-5 {
        width: 20%;
        padding-left: 0px;
    }
    #formSignUp form .checkbox .row {
        width: 200%;
    }
    #formSignUp form .checkbox .row .col-xs-7 {
        width: 200px;
        padding-left: 0px;
    }
    #formSignUp form .checkbox .pull-right.text-danger {
        text-decoration: none;
        color: white;
    }
    #formSignUp form .checkbox .checkbox-inline, #formSignUp .text-center{
        color: #000000;
    }
</style>
<div id="formSignUp">
    <form id="validate" class="form" method="post"  target="ifrmEdit" action="/submit-price-quote.html">
        <h2 class="text-center"><?php echo $this->translate->_('travel_with_confidence_button');?></h2>
        <div class="checkbox">
            <label class="text-info checkbox-inline">
                <div class="row">
                    <div class="col-xs-5"><b><?php echo $this->translate->_('common_service');?>: </b></div>
                    <div class="col-xs-7">
                        <input type="checkbox" class="validate[required]" value="<?php echo $this->translate->_('admin_resource_value');?>" name="s[]">
                        <?php echo $this->translate->_('admin_resource_value');?><br>
                        <input type="checkbox" value="<?php echo $this->translate->_('common_travel_tickets');?>" name="s[]">
                        <?php echo $this->translate->_('common_travel_tickets');?><br>
                        <input type="checkbox" value="<?php echo $this->translate->_('admin_resource_feature');?>" name="s[]">
                        <?php echo $this->translate->_('admin_resource_feature');?><br>
                        <input type="checkbox" value="<?php echo $this->translate->_('common_hotel');?>" name="s[]"> <?php echo $this->translate->_('common_hotel');?>
                    </div>
                </div>
            </label>
        </div>
        <div class="form-group">
            <input type="text" class="form-control validate[required]" name="n" placeholder="<?php echo $this->translate->_('admin_common_full_name');?>">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" name="p" id="pwd1" placeholder="<?php echo $this->translate->_('common_phone');?>">
        </div>
        <div class="form-group">
            <input type="text" class="form-control validate[required,custom[email]]]" name="m" placeholder="Email">
        </div>
        <div class="form-group">
            <textarea class="form-control" rows="5" name="d" style="resize: none;" placeholder="<?php echo $this->translate->_('admin_common_content');?>"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success form-control" value="<?php echo $this->translate->_('contact_bt_send');?>"/>
        </div>

    </form>
    <iframe name="ifrmEdit" id="ifrmEdit" style="display:none "></iframe>
</div>
<div id="map" style="width:100%;height:100%;">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3875.4079008507433!2d109.20749094999336!3d13.754257890298481!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x316f6cc2c31a7805%3A0x6c702d15d13a1a33!2zMTc1IENoxrDGoW5nIETGsMahbmcsIE5ndXnhu4VuIFbEg24gQ-G7qywgVGjDoG5oIHBo4buRIFF1aSBOaMahbiwgQsOsbmggxJDhu4tuaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1547803223123"
            width="100%" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>