<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
    <a href="index.html" class="s-text16">
        Home
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <a href="blog.html" class="s-text16">
        Blog
        <i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
    </a>

    <span class="s-text17">
			Black Friday Guide: Best Sales & Discount Codes
		</span>
</div>

<!-- content page -->
<section class="bgwhite p-t-60 p-b-25">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-9 p-b-80">
                <div class="p-r-50 p-r-0-lg">
                    <div class="p-b-40">
                        <div class="blog-detail-img wrap-pic-w" >
                            <?php echo $this->image($this->data[DbTable_Watch::COL_WATCH_IMAGE])?>
                        </div>
                        <div class="blog-detail-txt p-t-33">
                            <h4 class="p-b-11 m-text24">
                                <?php echo $this->data[DbTable_Watch::COL_WATCH_NAME]; ?>
                            </h4>


                            <p class="p-b-25">
                                <?php echo $this->data[DbTable_Watch::COL_WATCH_DESCRIPTION]; ?>

                            </p>


                        </div>

                    </div>

                </div>
            </div>

            <div class="col-md-4 col-lg-3 p-b-80">
                <div class="rightbar">
                    <!-- Categories -->
                    <h4 class="m-text23 p-t-56 p-b-34">
                        Thông số kỹ thuật
                    </h4>

                    <ul>
                        <li class="p-t-6 p-b-8 bo6">
                            <a href="#" class="s-text13 p-t-5 p-b-5">
                                <b>Loại kính:</b> <?php echo $this->data[DbTable_Watch::COL_WATCH_GLASSES]; ?>
                            </a>
                        </li>

                        <li class="p-t-6 p-b-8 bo7">
                            <a href="#" class="s-text13 p-t-5 p-b-5">
                                <b>Mặt kính:</b> <?php echo $this->data[DbTable_Watch::COL_WATCH_FACE]; ?>
                            </a>
                        </li>

                        <li class="p-t-6 p-b-8 bo7">
                            <a href="#" class="s-text13 p-t-5 p-b-5">
                                <b>Chống nước:</b> <?php echo $this->data[DbTable_Watch::COL_WATCH_WATERPROOF]; ?>
                            </a>
                        </li>

                        <li class="p-t-6 p-b-8 bo7">
                            <a href="#" class="s-text13 p-t-5 p-b-5">
                                <b>Size:</b> <?php echo $this->data[DbTable_Watch::COL_WATCH_SIZE]; ?>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>
</section>

