<?php if ($this->pageCount): ?>
    <div class="dataTables_paginate paging_simple_numbers" id="bootstrap-data-table-export_paginate">
        <ul class="pagination">
            <li class="paginate_button page-item previous disabled" id="bootstrap-data-table-export_previous">
            <?php if (isset($this->previous)): ?>
                <a href="<?php echo $this->currentFullUrl(array('page' => $this->previous)); ?>" aria-controls="bootstrap-data-table-export" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
            <?php endif ?>
                <?php foreach ($this->pagesInRange as $page): ?>
            <li>
                <?php if ($page != $this->current): ?>
                    <a href="<?php echo $this->currentFullUrl(array('page' => $page)); ?>" aria-controls="bootstrap-data-table-export" data-dt-idx="<?php echo $page; ?>" tabindex="0" class="page-link">
                        <?php echo $page; ?>
                    </a>
                <?php else: ?>
                    <?php echo $page; ?>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>

            <li class="paginate_button page-item next" id="bootstrap-data-table-export_next">
                <?php if (isset($this->next)): ?>
                    <a href="<?php echo $this->currentFullUrl(array('page' => $this->last)); ?>" aria-controls="bootstrap-data-table-export" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
                <?php endif ?>
            </li>
        </ul>
    </div>
<?php endif; ?>
