<div class="col-xs-12 col-sm-5">
    <p class="t_uper f_bol"><?php echo $this->translate->_('admin_login_forgot_password_header');?></p>
    <?php if($this->isError){ ?>
        <p class="bg-danger p10 r_color">
            <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
            <?php if ($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_EMAIL_NULL) {
                echo $this->translate->_('admin_login_forgot_password_err_email');
            } elseif ($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_EMAIL_INVALID) {
                echo $this->translate->_('admin_login_forgot_password_not_exist');
            } elseif($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_SUCCESSFUL) {
                echo $this->translate->_('admin_login_forgot_password_msg_success');
            } elseif($this->isError==Application_Constant_Module_Admin_Login_ForgotPassword::ERROR_CODE_CAPTCHA_INVALID) {
                echo $this->translate->_('login_index_msg_captcha_failed');
            } ?>
        </p>
    <?php } ?>
    <form action="/login/submit-forgot-password" id="validate" class="form" method="post">
        <div class="form-group mb10">
            <input type="text" name="email" required="required" id="loginEmail" placeholder="Email" class="w90p" />
        </div>
        <div class="row mt15">
            <div class="col-sm-6 col-xs-12">
                <div class="">
                    <input type="submit" value="<?php echo $this->translate->_('admin_login_forgot_password_button');?>" class="btn_action">
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 pt05">
                <a href="/login" class="fs12 m_color"><?php echo $this->translate->_('admin_login_layout_login');?></a>
            </div>
        </div>
    </form>
</div>
