Insert into content(content_id, content_title, content_created_at, content_original, fk_locale) values
(1, 'Thông tin liên hệ', sysdate(), 1, 1),
(2, 'Contact Us', sysdate(), 1, 2),
(3, 'Contact Us', sysdate(), 1, 3),
(4, 'Mang xa hoi', sysdate(), 4, 1),
(5, 'Social Network', sysdate(), 4, 2),
(6, 'Social Network', sysdate(), 4, 3),
(7, 'Lien he hop tac', sysdate(), 7, 1),
(8, 'Connect with us', sysdate(), 7, 2),
(9, 'Connect with us', sysdate(), 7, 3),
(10, 'Cau hoi thuong gap', sysdate(), 10, 1),
(11, 'FAQ', sysdate(), 10, 2),
(12, 'FAQ', sysdate(), 10, 3),
(13, 'Trang Blog', sysdate(), 13, 1),
(14, 'Blog', sysdate(), 13, 2),
(15, 'Blog', sysdate(), 13, 3),
(16, 'Chinh sach bao mat', sysdate(), 16, 1),
(17, 'Term', sysdate(), 16, 2),
(18, 'Term', sysdate(), 16, 3)
;