<div class="breadcrumbs">
    <div class="col-sm-8">
        <div class="page-header float-left">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Trang chủ</a></li>
                    <li><a href="/machine/edit">Danh mục</a></li>
                    <li class="active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <form>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="name" placeholder="Tìm kiếm tên sản phẩm..." value="<?php echo $this->name?>">
                    </div>
                    <div class="col-12 col-sm-2">
                        <select name="machineId" id="machineId" class="form-control">
                            <option value="0">Loại máy</option>
                            <?php foreach ($this->machineData as $machine){?>
                                <?php $select = $machine[DbTable_Machine::COL_MACHINE_ID] == $this->machineId ? 'selected' : ''?>
                                <option value="<?php echo $machine[DbTable_Machine::COL_MACHINE_ID]?>" <?php echo $select?>><?php echo $machine[DbTable_Machine::COL_MACHINE_NAME]?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="col-12 col-sm-2">
                        <select name="cordId" id="cordId" class="form-control">
                            <option value="0">Loại dây</option>
                            <?php foreach ($this->cordData as $cord){?>
                                <?php $select = $cord[DbTable_Cord::COL_CORD_ID] == $this->coreId ? 'selected' : ''?>
                                <option value="<?php echo $cord[DbTable_Cord::COL_CORD_ID]?>" <?php echo $select?>><?php echo $cord[DbTable_Cord::COL_CORD_NAME]?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="col-12 col-sm-2">
                        <select name="active" id="active" class="form-control">
                            <option value="-1">Tất cả</option>
                            <option value="1" <?php echo $this->active ==1 ? 'selected' : ''?>>Kích Hoạt</option>
                            <option value="0" <?php echo $this->active ==0 ? 'selected' : ''?>>Hủy Kết Hoạt</option>
                        </select>
                    </div>
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-outline-success">Tìm kiếm</button>
                    </div>
                </form>
                <br><br>
                <div class="col-sm-6">
                    <a href="/watch/edit"><button class="btn btn-success btn-sm">Thêm mới</button></a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"><input type="checkbox" class="check-all"></th>
                        <th scope="col">Tên đồng hồ</th>
                        <th scope="col">Loại Dây</th>
                        <th scope="col">Mặt đồng hồ</th>
                        <th scope="col">Loại Kính</th>
                        <th scope="col">Giá</th>
                        <th scope="col">Kích thước mặt</th>
                        <th scope="col">Bộ máy</th>
                        <th scope="col">Thể loại</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->pagination as $data) {?>
                        <tr>
                            <th scope="row"><input type="checkbox" class="check-items" value="<?php echo $data->{DbTable_Watch::COL_WATCH_ID}?>"></th>
                            <td><?php echo $data->{DbTable_Watch::COL_WATCH_NAME}?></td>
                            <td><?php echo $data->{DbTable_Cord::COL_CORD_NAME}?></td>
                            <td><?php echo $data->{DbTable_Watch::COL_WATCH_FACE}?></td>
                            <td><?php echo $data->{DbTable_Watch::COL_WATCH_GLASSES}?></td>
                            <td><?php echo $data->{DbTable_Watch::COL_WATCH_PRICE}?></td>
                            <td><?php echo $data->{DbTable_Watch::COL_WATCH_SIZE}?></td>
                            <?php
                            $active = $data->{DbTable_Watch::COL_WATCH_ACTIVE} == Application_Constant_Db_Config_Active::ACTIVE
                                ? 'Kích Hoạt' : 'Chưa Kích Hoạt';
                            ?>
                            <td><?php echo $active?></td>
                            <td>
                                <a href="/watch/edit/id/<?php echo $data->{DbTable_Watch::COL_WATCH_ID}?>">
                                    <button type="button" class="btn btn-link">
                                        <i class="fa fa-edit"></i> Edit
                                    </button>
                                </a>
                            </td>
                        </tr>
                    <?php }?>

                    </tbody>
                </table>
                <br>
                <div class="row">
                    <div class="col-sm-12 col-md-2">
                        <div class="dataTables_info" id="bootstrap-data-table-export_info" role="status" aria-live="polite">
                            <select name="manualUpdateElement" id="manualUpdateElement" class="form-control">
                                <option value="">Chọn</option>
                                <option value="inactivate">Hủy Kích Hoạt</option>
                                <option value="activate">Kích Hoạt</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-10">
                        <?php echo $this->pagination; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
