<section class="quote-full">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-5 col-lg-4">
                <div class="left-col item">
                    <div class="header">
                        <?php echo $this->translate->_('travel_with_confidence_header');?>
                    </div>
<!--                    <div class="sub-header">-->
<!--                        --><?php //echo $this->translate->_('travel_with_confidence_body');?>
<!--                    </div>-->
                    <div class="body">
                        <?php echo $this->translate->_('travel_with_confidence_content');?>
                    </div>
                    <a href="<?php echo $this->translate->_('search_now');?>" target="_blank"><button class="btn btn-default btn-lg"><?php echo $this->translate->_('travel_with_confidence_button');?></button></a>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-7 col-lg-8 hidden-xs">
                <div class="right-col item">
                </div>
            </div>
        </div>
    </div>
</section>
<br>