<section>
    <div class="key-point-wrapper">
        <img src="images/child-bg.jpg" alt="">
        <div class="black-cover"></div>
        <div class="container">
            <div class="key-point-content">
                <h1><?php echo $this->translate->_('feel_protected_vacation');?></h1>
                <p><?php echo $this->translate->_('understand_insurance_different_type');?></p>
                <div class="row">
                    <div class="col-sm-12 col-lg-6 col-lg-offset-3">
                        <a target="_blank" href="/price-quote.html"><button class="btn btn-warning btn-block"><span><?php echo $this->translate->_('index_quote_online');?></span> <span class="mdi mdi-arrow-right-box"></span></button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>