<!DOCTYPE html>
<html lang="en">
<head>
    <title>About</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.png"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/themify/themify-icons.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/elegant-font/html-css/style.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/slick/slick.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
    <!--===============================================================================================-->
</head>
<body class="animsition">


<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(images/heading-pages-06.jpg);">
    <h2 class="l-text2 t-center">
        About
    </h2>
</section>

<!-- content page -->
<section class="bgwhite p-t-66 p-b-38">
    <div class="container">
        <div class="wpb_text_column wpb_content_element ">
            <div class="wpb_wrapper">
                <p><strong>Được thành lập cách đây hơn 25 năm – vào những ngày cuối cùng của năm 1991, Đồng Hồ Hải Triều đã tồn tại và phát triển đến ngày nay và đang dần vươn lên trở thành 1 trong những nhà bán lẻ đồng hồ hàng đầu ở Việt Nam!</strong></p>
                <p><strong>Với tiêu chí phải luôn đem lại giá trị cao nhất cho khách hàng, Đồng Hồ Hải Triều không chỉ bán cho khách hàng những chiếc đồng hồ tốt nhất mà còn mang lại sự an tâm cho khách hàng khi sử dụng đồng hồ bằng các hình thức bảo hành, hậu mãi mà khó có thể tìm được ở bất kì đâu!</strong></p>
                <p><strong>Sự thoải mái, tiện lợi và tâm lý khách hàng luôn được đặt lên hàng đầu để khách hàng khi đến với Đồng Hồ Hải Triều sẽ luôn là những khoảnh khắc đáng nhớ lưu lại trong tâm trí khách hàng!</strong></p>
                <p><strong>Cùng với mục tiêu&nbsp;trở thành nhà bán lẻ đồng hồ hàng đầu Việt Nam, Đồng Hồ Hải Triều đã và đang không ngừng cải tiến chất lượng, dịch vụ, hậu mãi ngày càng tốt hơn để có thể đáp ứng mọi nhu cầu của khách hàng!</strong></p>

            </div>
        </div>
    </div>
</section>




<!-- Back to top -->
<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
</div>

<!-- Container Selection -->
<div id="dropDownSelect1"></div>
<div id="dropDownSelect2"></div>



<!--===============================================================================================-->
<script type="text/javascript" src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script type="text/javascript" src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script type="text/javascript" src="vendor/bootstrap/js/popper.js"></script>
<script type="text/javascript" src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script type="text/javascript" src="vendor/select2/select2.min.js"></script>
<script type="text/javascript">
    $(".selection-1").select2({
        minimumResultsForSearch: 20,
        dropdownParent: $('#dropDownSelect1')
    });

    $(".selection-2").select2({
        minimumResultsForSearch: 20,
        dropdownParent: $('#dropDownSelect2')
    });
</script>
<!--===============================================================================================-->
<script src="js/main.js"></script>

</body>
</html>
