


<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(images/heading-pages-06.jpg);">
    <h2 class="l-text2 t-center">
        About
    </h2>
</section>

<!-- content page -->
<section class="bgwhite p-t-66 p-b-38">
    <div class="container">
        <div class="row">
            <div class="col-md-4 p-b-30">
                <div class="hov-img-zoom">
                    <img src="images/banner-14.jpg" alt="IMG-ABOUT">
                </div>
            </div>

            <div class="col-md-8 p-b-30">
                <h3 class="m-text26 p-t-15 p-b-16">
                    GIỚI THIỆU
                </h3>

                <p class="p-b-28">
                    Những quan điểm kinh doanh dưới đây đều đã được các cán bộ, nhân viên của WATCH hiểu rõ, thấm nhuần và tuyệt đối tuân thủ theo:
                    * Không bán hàng kém chất lượng, hàng giả, hàng nhái, hàng không rõ nguồn gốc, xuất xứ...và để thiết thực nhất chúng tôi luôn cam kết “ Bồi thường gấp 10 lần giá trị thực nếu quý khách phát hiện mua phải hàng giả, hàng nhái từ chúng tôi”
                    * Luôn cung cấp cho các Quý khách hàng những sản phẩm tốt với giá cả cạnh tranh nhất đi kèm với những chế độ dịch vụ hoàn hảo nhất.
                    * Luôn đặt chữ tín lên hàng đầu, không vì lợi nhuận mà gian dối, lừa bịp Khách hàng...
                    * Luôn đặt mình vào địa vị của Khách hàng để có những quyết định, cư xử phải lẽ nhất...
                    * Luôn làm hài lòng mọi Khách hàng đến với WATCH bằng việc thấu hiểu và thực hiện theo quan điểm: "Khách hàng luôn luôn đúng".

                </p>

                <div class="bo13 p-l-29 m-l-9 p-b-10">
                    <p class="p-b-11">
                        1- Bán đúng giá cả: Quý khách hàng sẽ được bảo đảm về giá và Tuyệt đối không sợ bị hớ.
                        2- Đúng chất lượng: Quý khách hàng sẽ được đảm bảo về chất lượng hàng hóa bằng đúng tiêu chuẩn của hãng sản xuất và Đúng tính năng kỹ thuật như chúng tôi đã giới thiệu
                        3- Thái độ phục vụ: Quý khách hàng sẽ được WATCH phục vụ theo đúng phương châm Khách hàng là Thượng đế.
                        4- Dịch vụ hoàn hảo: Đến với WATCH quý khách sẽ được hưởng các chính sách, chế độ Dịch vụ hàng đầu tại Việt Nam.
                        5- Độ bền công ty: Với sự đầu tư cơ bản về cơ sở hạ tầng, với một ý thức trách nhiệm cao, chúng tôi muốn mang lại Sự an toàn tuyệt đối cho các Quý khách hàng đã mua hàng tại WATCH
                    </p>

                </div>
            </div>
        </div>
    </div>
</section>




<!-- Back to top -->
<div class="btn-back-to-top bg0-hov" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="fa fa-angle-double-up" aria-hidden="true"></i>
		</span>
</div>

<!-- Container Selection -->
<div id="dropDownSelect1"></div>
<div id="dropDownSelect2"></div>


