<?php echo $this->render('layout/page-slider.phtml');?>
<div class="" id="breadcrumb">
    <div class="container">
        <ul class="clearfix">
            <li class="breadcrumb_home">
                <a href="/"><i class="fa fa-home" aria-hidden="true"></i> <?php echo $this->translate->_('admin_resource_homepage');?> </a></li>
            <li>
                <a href="<?php echo $this->configUrl($this->config, 'about_us');?>"><?php echo $this->translate->_('admin_resource_about_us');?></a>
            </li>
            <?php
            $name = $this->infoCategory[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_NAME];
            $id = $this->infoCategory[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_ID];
            ?>
            <li><a href="<?php echo $this->aboutUsCategoryUrl($id, $name);?>"><?php echo $name; ?></a> </li>
            <li><span><?php echo $this->title;?></span></li>
        </ul>
        <a data-toggle="collapse" href="#sub_menu_item_collapse" aria-expanded="false" aria-controls="sub_menu_item_collapse" class="hidden-sm hidden-md hidden-lg collapsed" id="breadcrumb_btn_sub_menu"><i class="fa fa-caret-down" aria-hidden="true"></i></a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-3" id="side_left">
            <p class="title_sub_menu hidden-xs"><?php echo $this->translate->_('admin_resource_about_us');?></p>
            <ul class="sub_menu_item collapse in" id="sub_menu_item_collapse">
                <?php foreach ($this->menuAboutUsCategory as $category) { ?>
                    <?php
                    $name = $category[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_NAME];
                    $id = $category[DbTable_About_Us_Category::COL_ABOUT_US_CATEGORY_ID];
                    $url = $this->aboutUsCategoryUrl($id, $name);
                    $subData = isset($category['sub']) ? $category['sub'] : null;
                    ?>
                    <li>
                        <a href="<?php echo $url;?>" title="<?php echo $name;?>">
                            <?php echo $name;?>
                            <?php if ($subData && $this->categoryId == $id) { ?>
                                <span class="sub_menu_item_arrow">&gt;</span>
                            <?php } ?>
                        </a>
                        <?php if ($subData && $this->categoryId == $id) { ?>
                            <ul>
                                <?php foreach ($subData as $sub) { ?>
                                    <?php
                                    $subId = $sub[DbTable_About_Us_Sub_Category::COL_ABOUT_US_SUB_CATEGORY_ID];
                                    $subName = $sub[DbTable_About_Us_Sub_Category::COL_ABOUT_US_SUB_CATEGORY_NAME];
                                    $subUrl = $this->aboutUsSubCategoryUrl($id, $name, $subId, $subName);
                                    $subClassName = $this->subCategoryId == $subId ? ' class="active" ' : '';
                                    ?>
                                    <li<?php echo $subClassName;?>>
                                        <a href="<?php echo $subUrl;?>" title="<?php echo $subName;?>"><?php echo $subName;?></a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-9" id="page_container">
            <p class="mb20"><strong class="fs20"><?php echo $this->title;?></strong></p>
            <div class="fck-content"><?php echo $this->content;?></div>
            <?php echo $this->render('layout/add-this.phtml');?>
        </div>
    </div>
</div>