<div class="breadcrumbs">
    <div class="col-sm-8">
        <div class="page-header float-left">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="#">Trang chủ</a></li>
                    <li><a href="/category/edit">Danh mục</a></li>
                    <li class="active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <form>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Tìm kiếm tên danh mục...">
                    </div>
                    <div class="col-12 col-sm-2">
                        <select name="selectSm" id="SelectLm" class="form-control">
                            <option value="0">Active</option>
                            <option value="1">Unactive</option>
                        </select>
                    </div>
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-outline-success">Tìm kiếm</button>
                    </div>
                </form>
                <br><br>
                <div class="col-sm-6">
                    <a href="/category/edit"><button class="btn btn-success btn-sm">Thêm mới</button></a>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col"><input type="checkbox"></th>
                        <th scope="col">First</th>
                        <th scope="col">Last</th>
                        <th scope="col">Handle</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row"><input type="checkbox"></th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>
                            <a href="#">
                                <button type="button" class="btn btn-link">
                                <i class="fa fa-edit"></i> Edit
                            </button>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><input type="checkbox"></th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>
                            <a href="#">
                                <button type="button" class="btn btn-link">
                                    <i class="fa fa-edit"></i> Edit
                                </button>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><input type="checkbox"></th>
                        <td>Larry</td>
                        <td>the Bird</td>
                        <td>
                            <a href="#">
                                <button type="button" class="btn btn-link">
                                    <i class="fa fa-edit"></i> Edit
                                </button>
                            </a>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <div class="row">
                    <div class="col-sm-12 col-md-2">
                        <div class="dataTables_info" id="bootstrap-data-table-export_info" role="status" aria-live="polite">
                            <select name="selectSm" id="SelectLm" class="form-control">
                                <option value="">Chọn</option>
                                <option value="0">Active</option>
                                <option value="1">Unactive</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-10">
                        <div class="dataTables_paginate paging_simple_numbers" id="bootstrap-data-table-export_paginate">
                            <ul class="pagination">
                                <li class="paginate_button page-item previous disabled" id="bootstrap-data-table-export_previous">
                                    <a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                </li>
                                <li class="paginate_button page-item active"><a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="1" tabindex="0" class="page-link">1</a>
                                </li>
                                <li class="paginate_button page-item ">
                                    <a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="2" tabindex="0" class="page-link">2</a>
                                </li>
                                <li class="paginate_button page-item "><a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="3" tabindex="0" class="page-link">3</a>
                                </li>
                                <li class="paginate_button page-item ">
                                    <a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="4" tabindex="0" class="page-link">4</a>
                                </li>
                                <li class="paginate_button page-item ">
                                    <a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="5" tabindex="0" class="page-link">5</a>
                                </li><li class="paginate_button page-item "><a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="6" tabindex="0" class="page-link">6</a>
                                </li>
                                <li class="paginate_button page-item next" id="bootstrap-data-table-export_next">
                                    <a href="#" aria-controls="bootstrap-data-table-export" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
