<div style="clear: both"></div>
<?php $url = Application_Function_Common::fullCurrentUrl();?>
<div class="fb-share-button" style="float: right; margin-top: 30px" data-href="<?php echo $url;?>" data-layout="button" data-size="large" data-mobile-iframe="true">
    <a class="fb-xfbml-parse-ignore" style="background: #3b5998; color: #fff; padding: 5px 10px; border-radius:5px;" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $url;?>">Share on Facebook</a></div>
<div style="clear: both;"></div>